GET localhost:8088/test/ping
###
GET localhost:8088/test/list/member
###
GET localhost:8088/test/list/accountId
###
GET localhost:8088/test/list/houseId
###
POST localhost:8088/api/login
Content-Type: application/json

{
  "username": "wzy",
  "password": "123456"
}
###
GET localhost:8088/api/my/device
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzIiwic3ViIjoid3p5IiwiaWF0IjoxNzMwODExNjEyLCJleHAiOjE3MzA4MTg4MTIsInJvbGUiOiJhZG1pbiJ9.uJDzGZJEdOrWgAyADD8xZhYxXs61evR-PAd3TUb8U70
###
GET localhost:8088/api/my/device/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzIiwic3ViIjoid3p5IiwiaWF0IjoxNzMwODExNjEyLCJleHAiOjE3MzA4MTg4MTIsInJvbGUiOiJhZG1pbiJ9.uJDzGZJEdOrWgAyADD8xZhYxXs61evR-PAd3TUb8U70
###
GET localhost:8088/api/my/device/4/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzIiwic3ViIjoid3p5IiwiaWF0IjoxNzMwODExNjEyLCJleHAiOjE3MzA4MTg4MTIsInJvbGUiOiJhZG1pbiJ9.uJDzGZJEdOrWgAyADD8xZhYxXs61evR-PAd3TUb8U70





###
POST 47.108.27.238/api/login
Content-Type: application/json

{
  "username": "wzy",
  "password": "123456"
}

> {% client.global.set("remote-rust-token", response.body.data.token); %}
###
GET 47.108.27.238/api/my/device/4
Authorization: Bearer {{remote-rust-token}}
###
GET 47.108.27.238/api/my/device/4/status
Authorization: Bearer {{remote-rust-token}}
