GET localhost/test/ping
###
POST localhost/api/login
Content-Type: application/json

{
  "username": "wzy",
  "password": "123456"
}
###
GET localhost/api/my/device
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzIiwic3ViIjoid3p5IiwiaWF0IjoxNzMwNDI5NzQxLCJleHAiOjE3MzA0MzY5NDEsInJvbGUiOiJhZG1pbiJ9.RHd7uVMpAAkCsfwPa9ySaewp0hOTV7Hxx6PuRP9pIoQ
###
POST 47.108.27.238:80/api/login
Content-Type: application/json

{
  "username": "wzy",
  "password": "123456"
}
###
GET 47.108.27.238:80/api/my/device
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Mywic3ViIjoid3p5Iiwicm9sZSI6InVzZXIiLCJleHAiOjE3MzAzOTI2NDJ9.gZc_N4gTn9TFtN4FsN_HgTxXZzBBmoR2yPwaE5hx-T4
